### ISSUE TITLE
Compose file problem

### ISSUE THREAD

**Issue by p6002** [crocandr/docker-zerotier#2]
Your docker-compose file creates new connection every time container is up.

**Comment by crocandr** [comment]
Hi,

I don't understand your problem.
Please specify more.

**Comment by p6002** [comment]
Whenever I restart the container using docker compose, it connects to the zerotier network and gets a **new** IP address. 
For example, on another Synology server, I have zerotier set manually, without docker compose. When I restart the Synology, it gets the **same** IP address in zerotier. Docker compose should work the same way.

**Comment by crocandr** [comment]
I have tried but I did not get an error.

I have started with `docker-compose up -d` and stopped and deleted the container with the `docker-compose rm -v -f -s` command as you see on the image but I always get the same ID and same IP addresses on the ZeroTier portal.

![image](https://user-images.githubusercontent.com/7159285/210833942-3b06fa16-177a-4123-affd-d36e703d4cc9.png)

The status on the ZeroTier portal::
![image](https://user-images.githubusercontent.com/7159285/210834302-690c065b-ff1e-4572-879f-a62c0b8c3222.png)
![image](https://user-images.githubusercontent.com/7159285/210835283-1f37d391-a7c0-4ae3-81d7-6f02cdb12632.png)
![image](https://user-images.githubusercontent.com/7159285/210835697-fbd6c1be-1b8e-4c2c-a320-cb421a6d8521.png)


Here is my very simple docker-compose file:
```
version: '3'

services:
  zerotier:
    image: croc/zerotier
    environment:
      - NETWORK_ID=35c192ce9ba9ea5a
#      - ROUTES=10.10.12.0/23,10.147.20.115;10.10.14.0/23,10.147.20.220
#    volumes:
#      - './config/route.list:/config/route.list:ro'
    network_mode: host
    privileged: true
    restart: always
```
I've disabled all route option in this example because I don't use any.

I don't know why not work at your side. :(
